import assert from "node:assert/strict";
import test from "node:test";
import { acceptF3Render, adoptF2Snapshot, createF3RenderRequest, createF3State, hasNewerF2Snapshot, parseF3RenderResult, updateF3Config } from "../app/f3-finalization-model.ts";

const snapshot = (revision = 1, path = "POCHOPIT", identity = `snapshot-${revision}-${path}`) => ({ snapshotId: identity, canonicalNeed: { needId: "n1", needText: "Porozumět zahájení", initialF2Path: path, f3Target: path === "POZOROVAT" ? "pozorovací tabulka" : path === "VYTVOŘIT" ? "pracovní karty" : null }, initialPath: path, activePath: path, f3Target: path === "VYTVOŘIT" ? "pracovní karty" : null, hypotheses: [{ id: "h1", rank: 1, title: "Hypotéza", summary: "Význam", relevantNeeds: [], question: null, supportingInformation: [], limitations: [], unknowns: [], questions: [] }], activeSkills: [], skillParameters: {}, addedContext: [], processedBuild: { path, hypotheses: [], pathResult: path === "POCHOPIT" ? { kind: "understanding", relationships: [], comparisons: [], expertFrame: [], synthesis: "Význam" } : path === "POZOROVAT" ? { kind: "observation", purpose: "účel", observableIndicators: [], situations: [], comparisonConditions: [], scope: "týden", evidenceMethod: [], hypothesisLinks: [], limitations: [] } : { kind: "creation", pedagogicalObjective: "cíl", candidateApproaches: [], variantComparison: [], workingApproach: "karty", conditions: [], whatToVerify: [], relevantHypotheses: [], limitations: [] }, decisions: [], uncertainties: [], missingInformation: [], processedRevision: revision, processedResultId: `processed-${identity}` }, decisions: [], uncertainties: [], buildRevision: revision, processedRevision: revision });
const material = { kind: "material", title: "Výstup", introduction: "Úvod", sections: [], table: null, cards: [], usageNote: null };

test("F3 remains immutably bound until explicit snapshot adoption", () => { const a = snapshot(1); const b = snapshot(2); let state = createF3State(a); a.canonicalNeed.needText = "mutace"; assert.equal(state.sourceSnapshot.canonicalNeed.needText, "Porozumět zahájení"); assert.equal(hasNewerF2Snapshot(state, b), true); assert.equal(state.sourceSnapshotRevision, 1); state = adoptF2Snapshot(state, b); assert.equal(state.sourceSnapshotRevision, 2); });
test("format controls are local, preserve substantive snapshot and stale one render", () => { let calls = 0; let state = createF3State(snapshot()); const substantive = structuredClone(state.sourceSnapshot); const request = createF3RenderRequest(state); calls++; state = acceptF3Render(state, material, request); state = updateF3Config(state, { audience: "parent" }); state = updateF3Config(state, { languageStyle: "accessible", lengthDetail: "detailed", structureMode: "text" }); assert.equal(calls, 1); assert.deepEqual(state.sourceSnapshot, substantive); assert.equal(state.finalRender.content.title, "Výstup"); assert.equal(state.finalRender.status, "stale"); assert.equal(state.finalRender.staleReason, "configuration"); });
test("adopting a new preview preserves and marks render stale; successful regeneration refreshes it", () => { let state = createF3State(snapshot(1)); let request = createF3RenderRequest(state); state = acceptF3Render(state, material, request); state = adoptF2Snapshot(state, snapshot(2)); assert.equal(state.finalRender.status, "stale"); assert.equal(state.finalRender.staleReason, "source"); request = createF3RenderRequest(state); state = acceptF3Render(state, { ...material, title: "Nový" }, request); assert.equal(state.finalRender.status, "current"); assert.equal(state.finalRender.content.title, "Nový"); });
test("failed or superseded regeneration cannot replace the previous successful render", () => { let state = createF3State(snapshot()); const request = createF3RenderRequest(state); state = acceptF3Render(state, material, request); state = updateF3Config(state, { audience: "parent" }); state = acceptF3Render(state, { ...material, title: "Pozdní" }, request); assert.equal(state.finalRender.content.title, "Výstup"); });
test("same-configuration newer snapshot is detected and explicitly adopted without rendering", () => { let calls = 0; const a = snapshot(1, "POCHOPIT", "accepted-a"); const b = snapshot(1, "POCHOPIT", "accepted-b"); let state = createF3State(a); state = acceptF3Render(state, material, createF3RenderRequest(state)); assert.equal(hasNewerF2Snapshot(state, b), true); state = adoptF2Snapshot(state, b); assert.equal(state.sourceSnapshotId, "accepted-b"); assert.equal(state.finalRender.status, "stale"); assert.equal(state.finalRender.staleReason, "source"); assert.equal(calls, 0); });
test("F3 accepts both result variants and rejects malformed regeneration without replacing prior output", () => {
  assert.equal(parseF3RenderResult(material).kind, "material"); assert.equal(parseF3RenderResult({ kind: "boundary_issue", reason: "Chybí volba", affectedArea: "přístup", suggestedReturnToF2: "Doplňte přístup" }).kind, "boundary_issue");
  let state = createF3State(snapshot()); const request = createF3RenderRequest(state); state = acceptF3Render(state, material, request);
  for (const invalid of [{}, { kind: "unknown" }, { kind: "material", title: "neúplné" }, { kind: "boundary_issue", reason: "neúplné" }]) assert.throws(() => acceptF3Render(state, invalid, request), /neplatný F3/);
  assert.equal(state.finalRender.content.title, "Výstup");
});
